language: R
sudo: false
cache:
- packages
- pip

before_install:
  - sudo apt-get -y install libmariadbd-dev libmysqlclient-dev

r_packages:
- devtools
- RMySQL

r_github_packages:
- daroczig/logger

after_success:
- Rscript -e 'library(devtools);install();test()'
- Rscript -e 'covr::codecov()'

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

before_deploy: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
